name: ATPipi
version: 1.1
main: com.example.atpipi.ATPipiPlugin
api-version: 1.13

commands:
  atpipi:
    description: Пускать желтые блоки бетона из ног игрока.
    usage: /atpipi [off]
    permission: atpipi.use

permissions:
  atpipi.use:
    description: Разрешение на использование команды /atpipi
    default: true
